# Default values for zfs-snapshot-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Operator configuration
operator:
  # Operation mode: test, direct, or chroot
  # For Kubernetes deployments with hostPID, use chroot mode
  mode: chroot
  # Path to host root for chroot mode
  chrootHostPath: /host
  # Path to ZFS binaries in chroot mode
  chrootBinPath: /usr/local/sbin

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: ghcr.io/runningman84/zfs-snapshot-operator
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.0"
# CronJob configuration
cronjob:
  # Schedule in Cron format, see https://en.wikipedia.org/wiki/Cron
  schedule: "0 * * * *" # Run every hour
  # Number of successful finished jobs to retain
  successfulJobsHistoryLimit: 3
  # Number of failed finished jobs to retain
  failedJobsHistoryLimit: 3
  # Specifies how to treat concurrent executions of a Job
  concurrencyPolicy: Forbid
  # Suspend the CronJob
  suspend: false
  # Restart policy for the job
  restartPolicy: OnFailure
  # Enable hostPID to access host processes
  hostPID: true
  # Host path to mount
  hostPath: /
  # Mount path inside the container
  hostMountPath: /host
# Snapshot retention configuration
# Maximum number of snapshots to keep per frequency
snapshots:
  maxHourly: 24
  maxDaily: 7
  maxWeekly: 4
  maxMonthly: 12
  maxYearly: 3
# Pool filtering
# Comma-separated list of pools to manage snapshots for
# If empty, all pools will be managed
pools:
  whitelist: ""
  # Example: "tank,backup" to only manage tank and backup pools
  # Example: "" to manage all pools (default)
# Pool health monitoring
monitoring:
  # Number of days before warning about old scrubs (default: 90)
  scrubAgeThresholdDays: 90
# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""
# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created.
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account.
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template.
  name: ""
# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}
podSecurityContext:
  runAsNonRoot: false
  seccompProfile:
    type: RuntimeDefault
securityContext:
  allowPrivilegeEscalation: true
  capabilities:
    add:
      - SYS_ADMIN
      - SYS_CHROOT
  privileged: true
resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 64Mi
# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}
# For per-node deployment, specify the target node:
# kubernetes.io/hostname: nas-node-1

tolerations: []
affinity: {}
